version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8.17-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  gather:
    image: ubuntu:latest
    working_dir: /app
    command: /app/data-gather-analysis-gather-linux-amd64
    volumes:
      - ./build:/app
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - rabbitmq

  analysis:
    image: ubuntu:latest
    working_dir: /app
    command: /app/data-gather-analysis-analysis-linux-amd64
    volumes:
      - ./build:/app
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - rabbitmq

  display:
    image: ubuntu:latest
    working_dir: /app
    command: /app/data-gather-analysis-display-linux-amd64
    volumes:
      - ./build:/app
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    ports:
      - "8001:8001"
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - rabbitmq
